### PR TITLE
New syntax for providing per package paths

### PR DESCRIPTION
**Pull request by derhasi**
Like mentioned in #2 I would welcome to move to the composers/installers syntax.

This PR builds on top of #3.

### CODE REVIEW

**Comment by derhasi** [comment]
Alternatively we could use a totally different syntax, that would allow to add more functionality later, like "symlinking":

```json
"custom-installer": [
      {
        "pattern": "docroot/sites/all/modules/contrib/{$name}/",
        "filter": ["type:drupal-module"],
        "symlink": false
      },
      {
        "pattern": "docroot/sites/all/libraries/{$name}/",
        "filter": ["type:drupal-library", "phayes/geophp"],
        "symlink": true
      }
    ],
```

**Comment by derhasi** [comment]
Or maybe I dismiss the "symlink" idea and better put that in a separate composer plugin :)

**Comment by derhasi** [comment]
The [last commit](https://github.com/derhasi/custom-installer/commit/5e58497672984cfcf4819f9c6cfcd0d328a536d8) would fix https://github.com/davidbarratt/custom-installer/issues/5

**Comment by davidbarratt** [comment]
Closing an re-opening to hopefully invoke a Travis build of the PR...

**Comment by davidbarratt** [comment]
@derhasi,

Actually, can you re-open this on the new `develop` branch?

I can fix the coding standard errors there too.

Thanks!

**Comment by davidbarratt** [comment]
@derhasi,

Question... will this conflict with Composer Installers if they have both Custom Installer and Composer Installers running?

**Comment by derhasi** [comment]
I opened a new PR.

@davidbarratt It should not conflict, as long as both installers do not try to set the path for the same package. This would also be the case when `custom-installer-all-package-types` is set to `true`.

**Pull request closed without merging**
